# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSAuth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'OneTimePassword', '~> 3.0'
  pod 'ZBarSDK', '~> 1.3.1'
  pod 'Masonry', '~> 1.1.0'
  pod 'TrueTime'
  pod 'CryptoSwift', :git => "https://github.com/krzyzanowskim/CryptoSwift", :branch => "swift32"

  # Pods for iOSAuth

  target 'iOSAuthTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
